//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap04Lab01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autor
    {
        public Autor()
        {
            this.titleauthor = new HashSet<LivroAutor>();
        }
    
        public string AutorId { get; set; }
        public string Nome { get; set; }
        public string SobreNome { get; set; }
        public string phone { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string CEP { get; set; }
        public bool contract { get; set; }
    
        public virtual ICollection<LivroAutor> titleauthor { get; set; }
    }
}
