//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap04Lab01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editora
    {
        public Editora()
        {
            this.Livros = new HashSet<Livro>();
        }
    
        public string EditoraId { get; set; }
        public string EditoraNome { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
    
        public virtual ICollection<Livro> Livros { get; set; }
    }
}
