//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap04Lab01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public Livro()
        {
            this.titleauthor = new HashSet<LivroAutor>();
        }
    
        public string LivroId { get; set; }
        public string Titulo { get; set; }
        public string Tipo { get; set; }
        public string EditoraId { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<decimal> advance { get; set; }
        public Nullable<int> royalty { get; set; }
        public Nullable<int> ytd_sales { get; set; }
        public string Observacoes { get; set; }
        public System.DateTime DataPublicacao { get; set; }
    
        public virtual Editora publishers { get; set; }
        public virtual ICollection<LivroAutor> titleauthor { get; set; }
    }
}
