//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap04Lab01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivroAutor
    {
        public string AutorId { get; set; }
        public string LivroId { get; set; }
        public Nullable<byte> au_ord { get; set; }
        public Nullable<int> royaltyper { get; set; }
    
        public virtual Autor authors { get; set; }
        public virtual Livro titles { get; set; }
    }
}
