//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap06_Lab01_Teste.AwWebRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteAvulso", Namespace="http://schemas.datacontract.org/2004/07/Cap06Lab01.Models")]
    [System.SerializableAttribute()]
    public partial class ClienteAvulso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AwWebRef.IAdvWorksWcf")]
    public interface IAdvWorksWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvWorksWcf/ClientePaisLista", ReplyAction="http://tempuri.org/IAdvWorksWcf/ClientePaisListaResponse")]
        string[] ClientePaisLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvWorksWcf/ClientePaisLista", ReplyAction="http://tempuri.org/IAdvWorksWcf/ClientePaisListaResponse")]
        System.Threading.Tasks.Task<string[]> ClientePaisListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvWorksWcf/ClienteEstadoLista", ReplyAction="http://tempuri.org/IAdvWorksWcf/ClienteEstadoListaResponse")]
        string[] ClienteEstadoLista(string pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvWorksWcf/ClienteEstadoLista", ReplyAction="http://tempuri.org/IAdvWorksWcf/ClienteEstadoListaResponse")]
        System.Threading.Tasks.Task<string[]> ClienteEstadoListaAsync(string pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvWorksWcf/ClientesAvulsosPorPaisEstado", ReplyAction="http://tempuri.org/IAdvWorksWcf/ClientesAvulsosPorPaisEstadoResponse")]
        Cap06_Lab01_Teste.AwWebRef.ClienteAvulso[] ClientesAvulsosPorPaisEstado(string pais, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvWorksWcf/ClientesAvulsosPorPaisEstado", ReplyAction="http://tempuri.org/IAdvWorksWcf/ClientesAvulsosPorPaisEstadoResponse")]
        System.Threading.Tasks.Task<Cap06_Lab01_Teste.AwWebRef.ClienteAvulso[]> ClientesAvulsosPorPaisEstadoAsync(string pais, string estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdvWorksWcfChannel : Cap06_Lab01_Teste.AwWebRef.IAdvWorksWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdvWorksWcfClient : System.ServiceModel.ClientBase<Cap06_Lab01_Teste.AwWebRef.IAdvWorksWcf>, Cap06_Lab01_Teste.AwWebRef.IAdvWorksWcf {
        
        public AdvWorksWcfClient() {
        }
        
        public AdvWorksWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdvWorksWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvWorksWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvWorksWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] ClientePaisLista() {
            return base.Channel.ClientePaisLista();
        }
        
        public System.Threading.Tasks.Task<string[]> ClientePaisListaAsync() {
            return base.Channel.ClientePaisListaAsync();
        }
        
        public string[] ClienteEstadoLista(string pais) {
            return base.Channel.ClienteEstadoLista(pais);
        }
        
        public System.Threading.Tasks.Task<string[]> ClienteEstadoListaAsync(string pais) {
            return base.Channel.ClienteEstadoListaAsync(pais);
        }
        
        public Cap06_Lab01_Teste.AwWebRef.ClienteAvulso[] ClientesAvulsosPorPaisEstado(string pais, string estado) {
            return base.Channel.ClientesAvulsosPorPaisEstado(pais, estado);
        }
        
        public System.Threading.Tasks.Task<Cap06_Lab01_Teste.AwWebRef.ClienteAvulso[]> ClientesAvulsosPorPaisEstadoAsync(string pais, string estado) {
            return base.Channel.ClientesAvulsosPorPaisEstadoAsync(pais, estado);
        }
    }
}
