//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap05_Lab01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public Funcionario()
        {
            this.Employees1 = new HashSet<Funcionario>();
        }
    
        public int FuncionarioID { get; set; }
        public string SobreNome { get; set; }
        public string Nome { get; set; }
        public string Cargo { get; set; }
        public string Tratamento { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public Nullable<System.DateTime> DataAdmissao { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string CEP { get; set; }
        public string Pais { get; set; }
        public string TelefoneResidencial { get; set; }
        public string Ramal { get; set; }
        public byte[] Foto { get; set; }
        public string Observacoes { get; set; }
        public Nullable<int> ReportarPara { get; set; }
        public string FotoPath { get; set; }
    
        public virtual ICollection<Funcionario> Employees1 { get; set; }
        public virtual Funcionario Employees2 { get; set; }
    }
}
